[tools]
bun = "1.3.4"
go = "1.25.5"
golangci-lint = "2.7.2"

[env]
DATABASE_URL = "data/salmonstack.db"

# goose stuff
GOOSE_DRIVER = "sqlite3"
GOOSE_DBSTRING = "{{env.DATABASE_URL}}"
GOOSE_MIGRATION_DIR = "data/sql/migrations"
