// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buckets.sql

package models

import (
	"context"
)

const createBucket = `-- name: CreateBucket :one
INSERT INTO buckets (name) VALUES (?)
RETURNING id, name
`

func (q *Queries) CreateBucket(ctx context.Context, name string) (Bucket, error) {
	row := q.db.QueryRowContext(ctx, createBucket, name)
	var i Bucket
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getBucket = `-- name: GetBucket :one
SELECT id, name FROM buckets
WHERE id = ? LIMIT 1
`

func (q *Queries) GetBucket(ctx context.Context, id int64) (Bucket, error) {
	row := q.db.QueryRowContext(ctx, getBucket, id)
	var i Bucket
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listBuckets = `-- name: ListBuckets :many
SELECT id, name FROM buckets
`

func (q *Queries) ListBuckets(ctx context.Context) ([]Bucket, error) {
	rows, err := q.db.QueryContext(ctx, listBuckets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bucket
	for rows.Next() {
		var i Bucket
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
