// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: databases.sql

package models

import (
	"context"
)

const createDatabase = `-- name: CreateDatabase :one
INSERT INTO databases (name, subnet_id) VALUES (?, ?)
RETURNING id, name, subnet_id
`

type CreateDatabaseParams struct {
	Name     string
	SubnetID int64
}

func (q *Queries) CreateDatabase(ctx context.Context, arg CreateDatabaseParams) (Database, error) {
	row := q.db.QueryRowContext(ctx, createDatabase, arg.Name, arg.SubnetID)
	var i Database
	err := row.Scan(&i.ID, &i.Name, &i.SubnetID)
	return i, err
}

const getDatabase = `-- name: GetDatabase :one
SELECT id, name, subnet_id FROM databases
WHERE id = ? LIMIT 1
`

func (q *Queries) GetDatabase(ctx context.Context, id int64) (Database, error) {
	row := q.db.QueryRowContext(ctx, getDatabase, id)
	var i Database
	err := row.Scan(&i.ID, &i.Name, &i.SubnetID)
	return i, err
}

const listDatabases = `-- name: ListDatabases :many
SELECT id, name, subnet_id FROM databases
`

func (q *Queries) ListDatabases(ctx context.Context) ([]Database, error) {
	rows, err := q.db.QueryContext(ctx, listDatabases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Database
	for rows.Next() {
		var i Database
		if err := rows.Scan(&i.ID, &i.Name, &i.SubnetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
