// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domain_names.sql

package models

import (
	"context"
	"database/sql"
)

const createDomainName = `-- name: CreateDomainName :one
INSERT INTO domain_names (name, static_ip_id) VALUES (?, ?)
RETURNING id, name, static_ip_id
`

type CreateDomainNameParams struct {
	Name       string
	StaticIpID sql.NullInt64
}

func (q *Queries) CreateDomainName(ctx context.Context, arg CreateDomainNameParams) (DomainName, error) {
	row := q.db.QueryRowContext(ctx, createDomainName, arg.Name, arg.StaticIpID)
	var i DomainName
	err := row.Scan(&i.ID, &i.Name, &i.StaticIpID)
	return i, err
}

const getDomainName = `-- name: GetDomainName :one
SELECT id, name, static_ip_id FROM domain_names
WHERE id = ? LIMIT 1
`

func (q *Queries) GetDomainName(ctx context.Context, id int64) (DomainName, error) {
	row := q.db.QueryRowContext(ctx, getDomainName, id)
	var i DomainName
	err := row.Scan(&i.ID, &i.Name, &i.StaticIpID)
	return i, err
}

const listDomainNames = `-- name: ListDomainNames :many
SELECT id, name, static_ip_id FROM domain_names
`

func (q *Queries) ListDomainNames(ctx context.Context) ([]DomainName, error) {
	rows, err := q.db.QueryContext(ctx, listDomainNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainName
	for rows.Next() {
		var i DomainName
		if err := rows.Scan(&i.ID, &i.Name, &i.StaticIpID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
