// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: load_balancers.sql

package models

import (
	"context"
	"database/sql"
)

const createLoadBalancer = `-- name: CreateLoadBalancer :one
INSERT INTO load_balancers (name, subnet_id, static_ip_id) VALUES (?, ?, ?)
RETURNING id, name, subnet_id, static_ip_id
`

type CreateLoadBalancerParams struct {
	Name       string
	SubnetID   int64
	StaticIpID sql.NullInt64
}

func (q *Queries) CreateLoadBalancer(ctx context.Context, arg CreateLoadBalancerParams) (LoadBalancer, error) {
	row := q.db.QueryRowContext(ctx, createLoadBalancer, arg.Name, arg.SubnetID, arg.StaticIpID)
	var i LoadBalancer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SubnetID,
		&i.StaticIpID,
	)
	return i, err
}

const getLoadBalancer = `-- name: GetLoadBalancer :one
SELECT id, name, subnet_id, static_ip_id FROM load_balancers
WHERE id = ? LIMIT 1
`

func (q *Queries) GetLoadBalancer(ctx context.Context, id int64) (LoadBalancer, error) {
	row := q.db.QueryRowContext(ctx, getLoadBalancer, id)
	var i LoadBalancer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SubnetID,
		&i.StaticIpID,
	)
	return i, err
}

const listLoadBalancers = `-- name: ListLoadBalancers :many
SELECT id, name, subnet_id, static_ip_id FROM load_balancers
`

func (q *Queries) ListLoadBalancers(ctx context.Context) ([]LoadBalancer, error) {
	rows, err := q.db.QueryContext(ctx, listLoadBalancers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadBalancer
	for rows.Next() {
		var i LoadBalancer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SubnetID,
			&i.StaticIpID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
