// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: networks.sql

package models

import (
	"context"
)

const createNetwork = `-- name: CreateNetwork :one
INSERT INTO networks (name) VALUES (?)
RETURNING id, name
`

func (q *Queries) CreateNetwork(ctx context.Context, name string) (Network, error) {
	row := q.db.QueryRowContext(ctx, createNetwork, name)
	var i Network
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getNetwork = `-- name: GetNetwork :one
SELECT id, name FROM networks
WHERE id = ? LIMIT 1
`

func (q *Queries) GetNetwork(ctx context.Context, id int64) (Network, error) {
	row := q.db.QueryRowContext(ctx, getNetwork, id)
	var i Network
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listNetworks = `-- name: ListNetworks :many
SELECT id, name FROM networks
`

func (q *Queries) ListNetworks(ctx context.Context) ([]Network, error) {
	rows, err := q.db.QueryContext(ctx, listNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Network
	for rows.Next() {
		var i Network
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
