// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: servers.sql

package models

import (
	"context"
)

const createServer = `-- name: CreateServer :one
INSERT INTO servers (name) VALUES (?)
RETURNING id, name
`

func (q *Queries) CreateServer(ctx context.Context, name string) (Server, error) {
	row := q.db.QueryRowContext(ctx, createServer, name)
	var i Server
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getServer = `-- name: GetServer :one
SELECT id, name FROM servers
WHERE id = ? LIMIT 1
`

func (q *Queries) GetServer(ctx context.Context, id int64) (Server, error) {
	row := q.db.QueryRowContext(ctx, getServer, id)
	var i Server
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listServers = `-- name: ListServers :many
SELECT id, name FROM servers
`

func (q *Queries) ListServers(ctx context.Context) ([]Server, error) {
	rows, err := q.db.QueryContext(ctx, listServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Server
	for rows.Next() {
		var i Server
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
