// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: static_ips.sql

package models

import (
	"context"
)

const createStaticIP = `-- name: CreateStaticIP :one
INSERT INTO static_ips (name, ip_address) VALUES (?, ?)
RETURNING id, name, ip_address
`

type CreateStaticIPParams struct {
	Name      string
	IpAddress string
}

func (q *Queries) CreateStaticIP(ctx context.Context, arg CreateStaticIPParams) (StaticIp, error) {
	row := q.db.QueryRowContext(ctx, createStaticIP, arg.Name, arg.IpAddress)
	var i StaticIp
	err := row.Scan(&i.ID, &i.Name, &i.IpAddress)
	return i, err
}

const getStaticIP = `-- name: GetStaticIP :one
SELECT id, name, ip_address FROM static_ips
WHERE id = ? LIMIT 1
`

func (q *Queries) GetStaticIP(ctx context.Context, id int64) (StaticIp, error) {
	row := q.db.QueryRowContext(ctx, getStaticIP, id)
	var i StaticIp
	err := row.Scan(&i.ID, &i.Name, &i.IpAddress)
	return i, err
}

const listStaticIPs = `-- name: ListStaticIPs :many
SELECT id, name, ip_address FROM static_ips
`

func (q *Queries) ListStaticIPs(ctx context.Context) ([]StaticIp, error) {
	rows, err := q.db.QueryContext(ctx, listStaticIPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaticIp
	for rows.Next() {
		var i StaticIp
		if err := rows.Scan(&i.ID, &i.Name, &i.IpAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
