// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subnets.sql

package models

import (
	"context"
)

const createSubnet = `-- name: CreateSubnet :one
INSERT INTO subnets (name, network_id) VALUES (?, ?)
RETURNING id, name, network_id
`

type CreateSubnetParams struct {
	Name      string
	NetworkID int64
}

func (q *Queries) CreateSubnet(ctx context.Context, arg CreateSubnetParams) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, createSubnet, arg.Name, arg.NetworkID)
	var i Subnet
	err := row.Scan(&i.ID, &i.Name, &i.NetworkID)
	return i, err
}

const getSubnet = `-- name: GetSubnet :one
SELECT id, name, network_id FROM subnets
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSubnet(ctx context.Context, id int64) (Subnet, error) {
	row := q.db.QueryRowContext(ctx, getSubnet, id)
	var i Subnet
	err := row.Scan(&i.ID, &i.Name, &i.NetworkID)
	return i, err
}

const listSubnets = `-- name: ListSubnets :many
SELECT id, name, network_id FROM subnets
`

func (q *Queries) ListSubnets(ctx context.Context) ([]Subnet, error) {
	rows, err := q.db.QueryContext(ctx, listSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subnet
	for rows.Next() {
		var i Subnet
		if err := rows.Scan(&i.ID, &i.Name, &i.NetworkID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
